DROP SEQUENCE PLAY_SEQ;
CREATE SEQUENCE PLAY_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE PLAY_T;
CREATE TABLE PLAY_T (
  PLAY_NO    NUMBER NOT NULL,
  PLAYER     VARCHAR2(50 BYTE) NOT NULL, 
  AGE        NUMBER,
  GENDER     VARCHAR2(30 BYTE),
  CONSTRAINT PK_PLAY PRIMARY KEY (PLAY_NO)
);
-- 데이터 1번 추가
INSERT INTO PLAY_T (PLAY_NO, PLAYER, AGE, GENDER)
VALUES (PLAY_SEQ.NEXTVAL, 'John Doe', '30', 'Male');

-- 데이터 2번 추가
INSERT INTO PLAY_T (PLAY_NO, PLAYER, AGE, GENDER)
VALUES (PLAY_SEQ.NEXTVAL, 'Jane Smith', '28', 'Female');
